import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">PaymentsDeposit</Link>
        </li>
        <li>
          <Link to="/cover">Cover</Link>
        </li>
        <li>
          <Link to="/footerone">FooterOne</Link>
        </li>
        <li>
          <Link to="/textstyle">TextStyle</Link>
        </li>
        <li>
          <Link to="/pwaone">PWAOne</Link>
        </li>
        <li>
          <Link to="/sizes">Sizes</Link>
        </li>
        <li>
          <Link to="/footer">Footer</Link>
        </li>
        <li>
          <Link to="/search">Search</Link>
        </li>
        <li>
          <Link to="/banner1264x400main">Banner1264x400main</Link>
        </li>
        <li>
          <Link to="/one">One</Link>
        </li>
        <li>
          <Link to="/one1">One1</Link>
        </li>
        <li>
          <Link to="/pwa">PWA</Link>
        </li>
        <li>
          <Link to="/withoutsidebarthree">WithoutsidebarThree</Link>
        </li>
        <li>
          <Link to="/withoutsidebartwo">WithoutsidebarTwo</Link>
        </li>
        <li>
          <Link to="/withoutsidebar">Withoutsidebar</Link>
        </li>
        <li>
          <Link to="/withoutsidebarsix">WithoutsidebarSix</Link>
        </li>
        <li>
          <Link to="/withoutsidebarfive">WithoutsidebarFive</Link>
        </li>
        <li>
          <Link to="/withoutsidebar1">Withoutsidebar1</Link>
        </li>
        <li>
          <Link to="/withoutsidebarsix1">WithoutsidebarSix1</Link>
        </li>
        <li>
          <Link to="/withoutsidebarone">WithoutsidebarOne</Link>
        </li>
        <li>
          <Link to="/withoutsidebarfive1">WithoutsidebarFive1</Link>
        </li>
        <li>
          <Link to="/withoutsidebarfour">WithoutsidebarFour</Link>
        </li>
        <li>
          <Link to="/withoutsidebarfour1">WithoutsidebarFour1</Link>
        </li>
        <li>
          <Link to="/termsandconditions">TermsandConditions</Link>
        </li>
        <li>
          <Link to="/faq">FAQ</Link>
        </li>
        <li>
          <Link to="/paymentswithrawals">PaymentsWithrawals</Link>
        </li>
        <li>
          <Link to="/registration1920">Registration1920</Link>
        </li>
        <li>
          <Link to="/registration1248">Registration1248</Link>
        </li>
        <li>
          <Link to="/login1920">Login1920</Link>
        </li>
        <li>
          <Link to="/login1248">Login1248</Link>
        </li>
        <li>
          <Link to="/page">Page</Link>
        </li>
        <li>
          <Link to="/page1">Page1</Link>
        </li>
        <li>
          <Link to="/vippopupnextlevel">VIPPopUPnextlevel</Link>
        </li>
        <li>
          <Link to="/withoutsidebarseven">WithoutsidebarSeven</Link>
        </li>
        <li>
          <Link to="/withoutsidebarone1">WithoutsidebarOne1</Link>
        </li>
        <li>
          <Link to="/withoutsidebartwo1">WithoutsidebarTwo1</Link>
        </li>
        <li>
          <Link to="/withoutsidebarthree1">WithoutsidebarThree1</Link>
        </li>
        <li>
          <Link to="/loginedone">LoginedOne</Link>
        </li>
        <li>
          <Link to="/guest">Guest</Link>
        </li>
        <li>
          <Link to="/recentlyplayed">RecentlyPlayed</Link>
        </li>
        <li>
          <Link to="/loginedtwo">LoginedTwo</Link>
        </li>
        <li>
          <Link to="/logined">Logined</Link>
        </li>
        <li>
          <Link to="/loginedthree">LoginedThree</Link>
        </li>
        <li>
          <Link to="/ceotextinfo">CEOTextInfo</Link>
        </li>
        <li>
          <Link to="/logined1">Logined1</Link>
        </li>
        <li>
          <Link to="/loginedfour">LoginedFour</Link>
        </li>
        <li>
          <Link to="/guest1">Guest1</Link>
        </li>
        <li>
          <Link to="/guestone">GuestOne</Link>
        </li>
        <li>
          <Link to="/search1">Search1</Link>
        </li>
        <li>
          <Link to="/search2">Search2</Link>
        </li>
        <li>
          <Link to="/loginedone1">LoginedOne1</Link>
        </li>
        <li>
          <Link to="/loginedsix">LoginedSix</Link>
        </li>
        <li>
          <Link to="/loginedtwo1">LoginedTwo1</Link>
        </li>
        <li>
          <Link to="/loginedfive">LoginedFive</Link>
        </li>
        <li>
          <Link to="/ten">Ten</Link>
        </li>
        <li>
          <Link to="/eight">Eight</Link>
        </li>
        <li>
          <Link to="/buttonopenarchive">Buttonopenarchive</Link>
        </li>
        <li>
          <Link to="/openarchivewithcomplitedpromo">
            Openarchivewithcomplitedpromo
          </Link>
        </li>
        <li>
          <Link to="/eight1">Eight1</Link>
        </li>
        <li>
          <Link to="/six">Six</Link>
        </li>
        <li>
          <Link to="/seven">Seven</Link>
        </li>
        <li>
          <Link to="/three">Three</Link>
        </li>
        <li>
          <Link to="/bannerthree">BannerThree</Link>
        </li>
        <li>
          <Link to="/bannerfive">BannerFive</Link>
        </li>
        <li>
          <Link to="/bannernine">BannerNine</Link>
        </li>
        <li>
          <Link to="/bannerone">BannerOne</Link>
        </li>
        <li>
          <Link to="/bannerseven">BannerSeven</Link>
        </li>
        <li>
          <Link to="/bannersix">BannerSix</Link>
        </li>
        <li>
          <Link to="/banner">Banner</Link>
        </li>
        <li>
          <Link to="/bannereight">BannerEight</Link>
        </li>
        <li>
          <Link to="/bannertwo">BannerTwo</Link>
        </li>
        <li>
          <Link to="/nine">Nine</Link>
        </li>
        <li>
          <Link to="/four">Four</Link>
        </li>
        <li>
          <Link to="/tournamentthree">TournamentThree</Link>
        </li>
        <li>
          <Link to="/two">Two</Link>
        </li>
        <li>
          <Link to="/seven1">Seven1</Link>
        </li>
        <li>
          <Link to="/four1">Four1</Link>
        </li>
        <li>
          <Link to="/two1">Two1</Link>
        </li>
        <li>
          <Link to="/five">Five</Link>
        </li>
        <li>
          <Link to="/nine1">Nine1</Link>
        </li>
        <li>
          <Link to="/bannerfour">BannerFour</Link>
        </li>
        <li>
          <Link to="/three1">Three1</Link>
        </li>
        <li>
          <Link to="/five1">Five1</Link>
        </li>
        <li>
          <Link to="/six1">Six1</Link>
        </li>
        <li>
          <Link to="/page2">Page2</Link>
        </li>
        <li>
          <Link to="/withoutsidebarnine">WithoutsidebarNine</Link>
        </li>
        <li>
          <Link to="/withoutsidebareight">WithoutsidebarEight</Link>
        </li>
        <li>
          <Link to="/withoutsidebareight1">WithoutsidebarEight1</Link>
        </li>
        <li>
          <Link to="/withoutsidebarseven1">WithoutsidebarSeven1</Link>
        </li>
        <li>
          <Link to="/sizesone">SizesOne</Link>
        </li>
        <li>
          <Link to="/pwa1920">PWA1920</Link>
        </li>
        <li>
          <Link to="/pwa1248">PWA1248</Link>
        </li>
        <li>
          <Link to="/prelouder">Prelouder</Link>
        </li>
        <li>
          <Link to="/banner1265x250">Banner1265x250</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
